### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by kreskoo** [codex-team/codex.media#477]
u
![Screenshot_1](https://user-images.githubusercontent.com/57587618/68546574-6dec9400-03e0-11ea-8d52-1ae34867219f.png)
![Screenshot_2](https://user-images.githubusercontent.com/57587618/68546579-7349de80-03e0-11ea-8518-1dbc07825ff0.png)
![Screenshot_3](https://user-images.githubusercontent.com/57587618/68546581-78a72900-03e0-11ea-90bc-dffae18d3177.png)

**Comment by kreskoo** [comment]
/home/ubuntu/.npm/_logs/2019-11-10T09_54_43_309Z-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.13.0
3 info using node@v13.1.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle codex.media@1.1.0~prebuild: codex.media@1.1.0
6 info lifecycle codex.media@1.1.0~build: codex.media@1.1.0
7 verbose lifecycle codex.media@1.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle codex.media@1.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm$
9 verbose lifecycle codex.media@1.1.0~build: CWD: /home/ubuntu/codex.media/www
10 silly lifecycle codex.media@1.1.0~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'npm run build_js && npm run build_css && npm run clean_prebuild'
10 silly lifecycle ]
11 silly lifecycle codex.media@1.1.0~build: Returned: code: 2  signal: null
12 info lifecycle codex.media@1.1.0~build: Failed to exec build script
13 verbose stack Error: codex.media@1.1.0 build: `npm run build_js && npm run build_css && npm run $
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-$
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-$
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid codex.media@1.1.0
15 verbose cwd /home/ubuntu/codex.media/www
16 verbose Linux 4.15.0-1051-aws
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v13.1.0
19 verbose npm  v6.13.0
20 error code ELIFECYCLE
21 error errno 2
22 error codex.media@1.1.0 build: `npm run build_js && npm run build_css && npm run clean_prebuild`
22 error Exit status 2
23 error Failed at the codex.media@1.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by kreskoo** [comment]
help please

**Comment by kreskoo** [comment]
FIX ERRORS
